### ISSUE TITLE
Hiii 

### ISSUE THREAD

**Issue by HASAN3DG** [smthemex/ComfyUI_Pic2Story#1]
Error occurred when executing Pic2Story:

Failed to import transformers.models.blip.image_processing_blip because of the following error (look up to see its traceback):
cannot import name 'validate_preprocess_arguments' from 'transformers.image_utils' (D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\image_utils.py)

**Comment by smthemex** [comment]
Hello, this issue is caused by the low version of your transformer, which can run on versions 4.37.2 and above.
 I see that you are using the "ComfyUI_windows_portable" version of comfyUI. You can try running "update_comfyui_and_python_dependencies.bat" in "D: /ComfyUI_windows_portable/update", 
or in the "D: /ComfyUI_windows_portable/ python_embeded" directory, open CMD and run D:/ComfyUI_windows_portable/python_embeded/Python pip install transformer==4.37.2 -- target=" D: \ ComfyUI_windows_portable \python_embeded\Lib\site-packages"

**Comment by HASAN3DG** [comment]
Thanks Bro Done
